# only manual
trigger: none
pr: none

parameters:
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: "METHOD"
    displayName: "METHOD"
    type: string
    default: TRAFFIC_ROUTING
    values:
      - TRAFFIC_ROUTING
      - SWAP
  - name: "SWAP"
    displayName: 'SWAP'
    type: boolean
    default: false
    values:
      - False
      - True

variables:
  TIME_OUT: 5

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: set_app_routing
    jobs: 
      - job: release_routing
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'U87-PagoPa-PCI-uat(e7feb90c-fcc2-40a2-ba56-d68ec301c6c0)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                for app in $(APP_SERVICES); do
                  echo "Set routing to -> $(TRAFFIC_ROUTING) of $app"
                  az webapp traffic-routing set --distribution release=$(TRAFFIC_ROUTING) \
                    --name $app \
                    --resource-group U87-PM-AppServices-pci-uat \
                    --subscription "U87-PagoPa-PCI-uat"
                  if $[ $? == 0 ]; then
                    echo "ROUTED $app"
                  fi  
                done


  - stage: swap_app_services
    dependsOn: [set_app_routing]
    jobs: 
      - job: release_swap
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'U87-PagoPa-PCI-uat(e7feb90c-fcc2-40a2-ba56-d68ec301c6c0)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                if [ $(SWAP) ]; then
                  for app in $(APP_SERVICES); do
                    echo "SWAPPING $app"
                    az webapp deployment slot swap -s release \
                      --name $app \
                      --resource-group U87-PM-AppServices-pci-uat \
                      --subscription "U87-PagoPa-PCI-uat"
                    if $[ $? == 0 ]; then
                      echo "SWAPPED $app"
                    fi                      
                  done
                fi