# only manual
trigger: none
pr: none

parameters:
  - name: 'ENVIRONMENT'
    displayName: 'Run on selected environment'
    type: string
    default: uat
    values:
      - uat
      - prod
  - name: "METHOD"
    displayName: "METHOD"
    type: string
    default: TRAFFIC_ROUTING
    values:
      - TRAFFIC_ROUTING
      - SWAP
  - name: "TRAFFIC_ROUTING_VALUE_PERCENT"
    displayName: "TRAFFIC_ROUTING_VALUE_PERCENT" 
    type: number
    default: 10
  - name: "pm-appsrv-admin-panel"
    displayName: "admin-panel"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-batch"
    displayName: "batch"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-logging"
    displayName: "logging"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-payment-gateway"
    displayName: "payment-gateway"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-restapi-io"
    displayName: "restapi-io"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-restapi"
    displayName: "restapi"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-rtd"
    displayName: "rtd"
    type: boolean
    default: False
    values:
      - True
      - False
  - name: "pm-appsrv-wisp"
    displayName: "wisp"
    type: boolean
    default: False
    values:
      - True
      - False


variables:
  TIME_OUT: 5

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: set_app_routing
    jobs: 
      - job: release_routing
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'U87-PagoPa-PCI-uat(e7feb90c-fcc2-40a2-ba56-d68ec301c6c0)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                echo "${ parameters.pm-appsrv-logging }"; exit 0;
                


