# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

variables:
  TIME_OUT: 5

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: set_app_routing
    jobs: 
      - job: Bash@admin-panel-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-admin-panel-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@batch-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-batch-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@logging-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-logging-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@restapi-io-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-restapi-io-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@restapi-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-restapi-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@rtd-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-rtd-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"
      - job: Bash@wisp-release-routing
        steps:
        - bash: az webapp traffic-routing set --distribution release=$[variable.TRAFFIC_ROUTING] --name pm-appsrv-wisp-uat --resource-group U87-PM-AppServices-pci-uat --subscription \"U87-PagoPa-PCI-uat\"


